sudo: true
language: python
python:
  - "3.6"
services:
  - docker
script:
  - ./build.sh $TRAVIS_TAG
after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    - docker login --username $USERNAME --password $PASSWORD
    - ./push_to_docker_hub.sh $TRAVIS_TAG
    fi
