services:
  - docker
script:
  - ./build.sh $TRAVIS_TAG
after_success:
  - if [ "$TRAVIS_TAG" != "" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    ./push_to_docker_hub.sh $TRAVIS_TAG;
    fi